version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    command: --skip-ssl

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8009:8009"
    depends_on:
      - mysql
    volumes:
      - ../tmp_imgs:/app/tmp_imgs
      - ../front_img:/app/front_img
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: