# config
server_port: 8009
server_host: "0.0.0.0"
mysql: "mysql+pymysql://root:123456@localhost:3306/2026start_v3"

mysql_sys: "mysql+pymysql://root:123456@localhost:3306/data_copilot_v10_sys"

static_path: "http://127.0.0.1:8009/"
static_folder: "tmp_imgs"

model_name: "deepseek-v4-flash"
# qwen3.7-flash qwen3.8-max
# glm-4
# deepseek-chat deepseek-v4-flash deepseek-v4-pro
# qwen-max
# gpt-4o-mini

# model_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
model_url: "https://tokenhub.tencentmaas.com/v1"
# model_url: "https://llm-giu1hmeshaf2grh0.cn-beijing.maas.aliyuncs.com/compatible-mode/v1"
# https://open.bigmodel.cn/api/paas/v4/
# https://api.deepseek.com/v1/
# https://dashscope.aliyuncs.com/compatible-mode/v1
# https://api.openai.com/v1
